/* Persistent identity, reviewed episodes, exact email approval and chip discovery. */
(()=>{
const post=(route,body={})=>api('/api/navi/'+route,'POST',body);
const wrap=(fn,target='navi-status')=>async e=>{try{await fn(e);}catch(x){$(target).textContent=x.message;}};
const button=(label,fn)=>{const b=node('button',label,'quiet');b.type='button';b.onclick=wrap(fn);return b;};
let persona=null,approval=null;
function localTime(seconds){const d=new Date(seconds*1000);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}
function renderPersona(p){persona=p;document.body.dataset.naviName=p.name;for(const label of document.querySelectorAll('.assistant .message-label'))label.textContent=p.name;$('persona-name').value=p.name;$('persona-user').value=p.user_name;$('persona-mood').value=p.mood;$('persona-activity').checked=p.remember_activity;$('persona-retention').value=p.retention_days;$('persona-continuity').textContent=p.name+' · '+p.familiarity+' · '+p.days_together+' remembered active day(s).';if(p.onboarded){$('navi-welcome').hidden=false;$('navi-welcome').textContent=(p.user_name?'Hi '+p.user_name+'. ':'')+'I’m '+p.name+'. What shall we work on today?';}}
async function loadPersona(){const s=await api('/api/navi');renderPersona(s.persona);return s;}
$('onboarding-skip').onclick=()=>{sessionStorage.setItem('nexo-onboarding-later','1');$('navi-onboarding').close();};
$('navi-onboarding').addEventListener('cancel',()=>sessionStorage.setItem('nexo-onboarding-later','1'));
$('onboarding-form').onsubmit=wrap(async e=>{e.preventDefault();await api('/api/preferences','POST',{personality:$('onboarding-tone').value});renderPersona(await post('persona',{name:$('onboarding-name').value,user_name:$('onboarding-user').value,onboarded:true,remember_activity:$('onboarding-remember').checked}));$('navi-onboarding').close();$('prompt').focus();},'onboarding-status');
$('persona-form').onsubmit=wrap(async e=>{e.preventDefault();renderPersona(await post('persona',{name:$('persona-name').value,user_name:$('persona-user').value,mood:$('persona-mood').value,remember_activity:$('persona-activity').checked,retention_days:Number($('persona-retention').value),onboarded:true}));$('navi-status').textContent='Identity saved on this device.';});
function resetEpisode(){$('episode-form').reset();$('episode-id').value='';$('episode-when').value=localTime(Date.now()/1000);}
async function episodes(){const result=await post('episodes/list');$('episode-list').replaceChildren();for(const r of result.episodes){const card=node('div','','navi-row');card.append(node('strong',r.what),node('p',new Date(r.occurred*1000).toLocaleString()+(r.people?' · '+r.people:'')),node('p',r.kind+' · '+r.occurrences+' occurrence(s) · '+(r.pinned?'Kept until you delete it':'Expires '+new Date(r.expires*1000).toLocaleDateString()),'small muted'));
if(r.kind!=='activity')card.append(button('Edit',()=>{$('episode-id').value=r.id;$('episode-what').value=r.what;$('episode-people').value=r.people;$('episode-when').value=localTime(r.occurred);$('episode-kind').value=r.kind;$('episode-pin').checked=r.pinned;$('episode-form').scrollIntoView({block:'center'});}));
card.append(button('Forget',async()=>{if(!confirm('Forget this experience?'))return;await post('episodes/forget',{id:r.id,confirm:true});await episodes();}));$('episode-list').append(card);}if(!result.episodes.length)$('episode-list').append(node('p','No saved experiences yet.'));}
$('episode-form').onsubmit=wrap(async e=>{e.preventDefault();const data={what:$('episode-what').value,people:$('episode-people').value,occurred:new Date($('episode-when').value).getTime()/1000,kind:$('episode-kind').value,pinned:$('episode-pin').checked};if($('episode-id').value)data.id=$('episode-id').value;await post('episodes/save',data);resetEpisode();await episodes();$('episode-status').textContent='Reviewed experience saved. You can correct or forget it at any time.';},'episode-status');
$('episode-cancel').onclick=resetEpisode;$('episode-refresh').onclick=wrap(episodes,'episode-status');
$('episode-clean').onclick=wrap(async()=>{const p=await post('episodes/preview');if(!confirm(p.expired+' expired memories and '+p.duplicates+' exact duplicate memories will be removed. '+p.notice))return;const r=await post('episodes/maintain',{confirm:true});$('episode-status').textContent='Cleanup completed: '+r.expired+' expired, '+r.duplicates+' duplicates.';await episodes();await loadPersona();},'episode-status');
$('episode-forget').onclick=wrap(async()=>{if(!confirm('Forget ALL experiences and remembered active days? Saved Library notes and your chosen name remain.'))return;await post('episodes/forget',{id:'all',confirm:true});await episodes();await loadPersona();},'episode-status');
function clearMail(){$('mail-form').reset();$('mail-id').value='';approval=null;if($('mail-review').open)$('mail-review').close();$('mail-review-content').textContent='';}
async function mailList(){const data=await post('mail/list');$('mail-mode').value=data.mode;$('mail-list').replaceChildren();for(const d of data.drafts){const card=node('div','','navi-row');card.append(node('strong',d.subject),node('p','From: '+d.sender+'\nTo: '+d.to),node('p',d.state));if(d.state==='delivery-unknown')card.append(node('p','Check Gmail Sent before making another draft. This message will not be retried.'));if(d.state==='draft'){card.append(button('Edit local draft',()=>{for(const key of ['id','sender','to','subject','text'])$('mail-'+key).value=d[key];}),button('Review for sending',async()=>{approval=await post('mail/preview',{id:d.id});$('mail-review-content').textContent='From: '+approval.sender+'\nTo: '+approval.to+'\nSubject: '+approval.subject+'\n\n'+approval.text;$('mail-review-status').textContent='';$('mail-review').showModal();}));}card.append(button('Delete local draft',async()=>{if(!confirm('Remove this local draft record? This does not delete anything in Gmail.'))return;await post('mail/remove',{id:d.id,confirm:true});clearMail();await mailList();}));$('mail-list').append(card);}}
$('mail-mode-save').onclick=wrap(async()=>{await post('mail/mode',{mode:$('mail-mode').value});clearMail();await mailList();$('mail-status').textContent='Mail access level saved. Sending still needs its own Google connection and each-message confirmation.';},'mail-status');
$('mail-form').onsubmit=wrap(async e=>{e.preventDefault();const body={};for(const key of ['sender','to','subject','text'])body[key]=$('mail-'+key).value;if($('mail-id').value)body.id=$('mail-id').value;await post('mail/save',body);clearMail();await mailList();$('mail-status').textContent='Draft saved locally. Nothing was sent.';},'mail-status');
$('mail-use-reply').onclick=wrap(()=>{const reply=[...conversation].reverse().find(x=>x.role==='assistant');if(!reply)throw Error('Ask for an email draft in Chat first');clearMail();$('mail-text').value=reply.content.slice(0,6000);$('mail-status').textContent='Review and edit this text, fill From and To, then save. Nothing was sent.';},'mail-status');
$('mail-clear').onclick=clearMail;$('mail-refresh').onclick=wrap(mailList,'mail-status');$('mail-cancel').onclick=()=>{approval=null;$('mail-review').close();};
$('mail-send').onclick=wrap(async()=>{if(!approval)throw Error('Review the draft again');const current=approval;approval=null;$('mail-send').disabled=true;try{await post('mail/send',{approval:current.approval,confirm:true});$('mail-review').close();$('mail-status').textContent='Gmail accepted the message.';await mailList();}finally{$('mail-send').disabled=false;}},'mail-review-status');
$('navi-vault-lock').addEventListener('click',()=>{clearMail();$('mail-list').replaceChildren();});
function downloadChip(result){const data=Uint8Array.from(atob(result.data),c=>c.charCodeAt(0)),url=URL.createObjectURL(new Blob([data],{type:'application/zip'})),a=node('a','');a.href=url;a.download=result.filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function catalog(){const result=await post('catalog');$('catalog-list').replaceChildren();for(const c of result.chips){const card=node('div','','navi-row');card.append(node('strong',c.name+(c.installed?' · Installed':'')),node('p',c.description),node('p','Permissions: '+(c.permissions.join(', ')||'None'),'small muted'));if(c.installed)card.append(button('Download signed chip to share',async()=>downloadChip(await post('chips/export',{name:c.name}))));else card.append(button('Download and inspect',async()=>{await api('/api/trust/permissions','POST',{scope:'network.chips',enabled:true});const p=await post('catalog/download',{name:c.name});card.append(node('pre','Publisher fingerprint: '+p.fingerprint+'\nSHA-256: '+p.sha256),button('Install this reviewed chip',async()=>{if(!confirm('Install '+c.name+' with permissions: '+c.permissions.join(', ')+'? A signature identifies a key, not a verified person.'))return;await api('/api/trust/permissions','POST',{scope:'chips.install',enabled:true});await post('chips/install',{data:p.data,fingerprint:p.fingerprint,consent:true});await catalog();$('catalog-status').textContent='Installed. Reopen Navi to refresh the chip runner.';}));}));$('catalog-list').append(card);}}
$('catalog-refresh').onclick=wrap(catalog,'catalog-status');
$('navi-tab').addEventListener('click',wrap(loadPersona));resetEpisode();
api('/api/status').then(async s=>{if(!s.desktop)return;const state=await loadPersona();if(!state.persona.onboarded&&!sessionStorage.getItem('nexo-onboarding-later'))$('navi-onboarding').showModal();}).catch(()=>{});
})();
