/* Optional modules. Shares the existing authenticated local API; no cloud voice APIs. */
(()=>{
let snapshot=null,chipPreview=null,chipData='',imported=null,recording=null,audioURL=null,polling=false;
const post=(route,body={})=>api('/api/navi/'+route,'POST',body);
const status=text=>{$('navi-status').textContent=text;};
const attempt=fn=>async event=>{try{await fn(event);}catch(e){status(e.message);$('navi-record-status').textContent=e.message;}};
async function grant(scope,enabled=true){await api('/api/trust/permissions','POST',{scope,enabled});}
async function settings(values){return post('settings',{settings:values});}
const bytes64=bytes=>{let text='';for(let i=0;i<bytes.length;i+=8192)text+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(text);};
function download(value,name){const u=URL.createObjectURL(new Blob([JSON.stringify(value)],{type:'application/json'}));const a=node('a','');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function button(label,action){const b=node('button',label,'quiet');b.type='button';b.onclick=attempt(action);return b;}
function notices(items){
 $('navi-notifications').replaceChildren();
 for(const item of items){const row=node('div','','navi-row');row.append(node('strong',item.title),node('p',item.body));if(!item.seen){row.append(button('Mark read',async()=>{await post('seen',{id:item.id});await refresh();}));if('Notification'in window&&Notification.permission==='granted'&&!sessionStorage.getItem('nexo-notice-'+item.id)){new Notification(item.title,{body:item.body.slice(0,300),tag:item.id});sessionStorage.setItem('nexo-notice-'+item.id,'1');}}$('navi-notifications').append(row);}
 if(!items.length)$('navi-notifications').append(node('p','Nothing waiting. Your reminders will appear here.','muted'));
}
async function refresh(){
 snapshot=await api('/api/navi');const s=snapshot.settings;
 for(const key of ['avatar','voice','scheduler','briefing'])$('navi-'+key).checked=s[key];
 $('navi-voice-toolbar').hidden=!s.voice;
 for(const key of ['voice_language','briefing_time','timezone','briefing_note'])$('navi-'+key.replaceAll('_','-')).value=s[key];
 for(const key of ['briefing_calendar','briefing_gmail'])$('navi-'+key.replaceAll('_','-')).checked=s[key];
 $('navi-presence').textContent='Currently '+snapshot.presence.state+'. '+(snapshot.presence.error||'');
 const voice=snapshot.voice,lang=voice.languages.find(x=>x.id===s.voice_language);
 $('navi-voice-status').textContent=voice.error||voice.progress||(lang?.installed?'Recognition ready.':'Recognition not downloaded.');$('navi-voice-install').disabled=voice.busy;
 $('navi-vault-status').textContent=snapshot.google.vault.unlocked?'Vault unlocked for this session.':'Vault locked. Google reads are unavailable.';
 $('navi-reminders').replaceChildren();for(const r of snapshot.reminders){const row=node('div','','navi-row');row.append(node('span',r.text+' · '+new Date(r.due*1000).toLocaleString()+(r.done?' · Delivered':'')),button('Remove',async()=>{await post('remove-reminder',{id:r.id});await refresh();}));$('navi-reminders').append(row);}
 notices(snapshot.notifications);
 $('navi-google').replaceChildren();for(const c of snapshot.google.connectors){const row=node('div','','navi-row');row.append(node('h3',c.name==='gmail'?'Gmail':'Google Calendar'),node('p',c.scope,'small muted'));
 row.append(button(c.connected?'Reconnect':'Connect read only',async()=>{await grant(c.permission);const result=await post('google/authorize',{service:c.name});const a=node('a','Continue to Google sign-in ↗');a.href=result.url;a.target='_blank';a.rel='noreferrer';row.append(a);a.click();status('Finish in your browser, then press Refresh connections.');}));
 if(c.connected){const label=node('label','');const toggle=document.createElement('input');toggle.type='checkbox';toggle.checked=c.enabled&&c.allowed;toggle.onchange=attempt(async()=>{await grant(c.permission,toggle.checked);await post('google/toggle',{service:c.name,enabled:toggle.checked});await refresh();});label.append(toggle,node('span',' Enabled'));row.append(label,button('Read recent items',async()=>{const result=await post('google/read',{service:c.name});$('navi-google-content').replaceChildren(node('p','External content · untrusted data'));for(const item of result.items){const entry=node('div','','navi-row');entry.append(node('strong',item.title||item.subject),node('p',item.start||item.from||''),node('p',item.description||item.snippet||''));if(item.security)entry.append(node('p',item.security.flags.join('\n')||'No heuristic flags. This does not prove the email is safe.'));$('navi-google-content').append(entry);}}),button('Revoke access',async()=>{if(!confirm('Disconnect this service and revoke its Google token?'))return;const result=await post('google/revoke',{service:c.name,consent:true});status(result.message);await refresh();}));}
 $('navi-google').append(row);}
 $('navi-google').append(button('Refresh connections',refresh));
 $('navi-chips').replaceChildren();$('navi-chip-run-select').replaceChildren();for(const c of snapshot.chips){const row=node('div','','navi-row');row.append(node('strong',c.manifest.name+(c.builtin?' · Built in':'')),node('p',c.invalid?'Signature or file invalid':c.manifest.permissions.join(', ')||'No additional permissions','small muted'));if(!c.builtin)row.append(button('Remove chip',async()=>{await grant('chips.install');await post('chips/remove',{name:c.manifest.name});await refresh();}));$('navi-chips').append(row);if(!c.invalid){const o=node('option',c.manifest.name);o.value=c.manifest.name;$('navi-chip-run-select').append(o);}}
}
$('navi-tab').onclick=attempt(async()=>{for(const id of ['chat','memory','workspace','setup']){$(id+'-view').hidden=true;$(id+'-tab').classList.remove('active');}$('navi-view').hidden=false;$('navi-tab').classList.add('active');$('page-title').textContent='Your Navi.';await refresh();try{const docs=await api('/api/documents');$('navi-briefing-note').replaceChildren(node('option','Library overview'));$('navi-briefing-note').firstChild.value='';for(const d of docs.documents){const o=node('option',d.title);o.value=d.id;$('navi-briefing-note').append(o);}$('navi-briefing-note').value=snapshot.settings.briefing_note;}catch{}});
for(const id of ['chat','memory','workspace','setup'])$(id+'-tab').addEventListener('click',()=>{$('navi-view').hidden=true;$('navi-tab').classList.remove('active');});
for(const [name,scope] of [['avatar','presence.use'],['voice','voice.use'],['scheduler','scheduler.use']])$('navi-'+name).onchange=attempt(async()=>{const enabled=$('navi-'+name).checked;await grant(scope,enabled);await settings({[name]:enabled});await refresh();});
$('navi-voice-language').onchange=attempt(async()=>{await settings({voice_language:$('navi-voice-language').value});await refresh();});
$('navi-voice-install').onclick=attempt(async()=>{await post('voice/install',{language:$('navi-voice-language').value});status('Downloading the local recognition model…');await refresh();});
$('navi-reminder-form').onsubmit=attempt(async e=>{e.preventDefault();await post('reminder',{text:$('navi-reminder-text').value,due:new Date($('navi-reminder-time').value).getTime()/1000});$('navi-reminder-text').value='';status('Reminder saved. Enable reminders to deliver it.');await refresh();});
$('navi-day-save').onclick=attempt(async()=>{await settings({briefing:$('navi-briefing').checked,briefing_time:$('navi-briefing-time').value,timezone:$('navi-timezone').value,briefing_calendar:$('navi-briefing-calendar').checked,briefing_gmail:$('navi-briefing-gmail').checked,briefing_note:$('navi-briefing-note').value});status('Briefing settings saved.');});
$('navi-brief-now').onclick=attempt(async()=>{await post('briefing');await refresh();});
$('navi-notifications-enable').onclick=attempt(async()=>{if(!('Notification'in window))throw Error('This browser does not support desktop notifications. Use the in-app list.');status('Notifications: '+await Notification.requestPermission());});
$('navi-vault-unlock').onclick=attempt(async()=>{const phrase=$('navi-vault-phrase').value;$('navi-vault-phrase').value='';await post('vault/unlock',{phrase});await refresh();});
$('navi-vault-lock').onclick=attempt(async()=>{await post('vault/lock');$('navi-google-content').replaceChildren();await refresh();});
$('navi-google-client').onchange=attempt(async()=>{const f=$('navi-google-client').files[0];if(!f||f.size>20000)throw Error('Choose the small Google Desktop client JSON file');const client=JSON.parse(await f.text());$('navi-google-client').value='';await post('google/configure',{client});status('Desktop OAuth client saved in the encrypted vault.');});
$('navi-chip-file').onchange=attempt(async()=>{chipPreview=null;$('navi-chip-install').disabled=true;const f=$('navi-chip-file').files[0];if(!f||f.size>100000)throw Error('Chip files must be at most 100 KB');chipData=bytes64(new Uint8Array(await f.arrayBuffer()));chipPreview=await post('chips/preview',{data:chipData});$('navi-chip-preview').textContent=JSON.stringify(chipPreview,null,2);$('navi-chip-consent').checked=false;$('navi-chip-install').disabled=false;});
$('navi-chip-install').onclick=attempt(async()=>{if(!chipPreview||!$('navi-chip-consent').checked)throw Error('Review and approve the exact chip first');await grant('chips.install');await post('chips/install',{data:chipData,fingerprint:chipPreview.fingerprint,consent:true});await refresh();status('Chip installed.');});
$('navi-chip-run').onclick=attempt(async()=>{const name=$('navi-chip-run-select').value;const chip=snapshot.chips.find(x=>x.manifest.name===name);if(!chip.builtin){if(!confirm('Allow installed declarative chips to run with their listed permissions?'))return;await grant('chips.run');}const result=await post('chips/run',{name,input:JSON.parse($('navi-chip-input').value)});$('navi-chip-result').textContent=JSON.stringify(result,null,2);});
$('navi-transfer-export').onclick=attempt(async()=>{if(!$('navi-transfer-consent').checked)throw Error('Approve the profile categories before export');await grant('transfer.export');const phrase=$('navi-transfer-phrase').value;$('navi-transfer-phrase').value='';const bundle=await post('transfer/export',{phrase,consent:true});download(bundle,'My-Navi.nexo');$('navi-transfer-status').textContent='Encrypted profile downloaded. Keep its phrase separately.';});
$('navi-transfer-import').onclick=attempt(async()=>{if(!$('navi-transfer-consent').checked)throw Error('Approve importing this profile first');const f=$('navi-transfer-file').files[0];if(!f||f.size>6000000)throw Error('Choose a .nexo profile file under 6 MB');await grant('transfer.import');const phrase=$('navi-transfer-phrase').value;$('navi-transfer-phrase').value='';imported=await post('transfer/import',{bundle:JSON.parse(await f.text()),phrase,consent:true});$('navi-transfer-status').textContent=imported.message+' '+imported.documents+' saved notes.';$('navi-transfer-switch').hidden=false;});
$('navi-transfer-switch').onclick=attempt(async()=>{if(!imported||!confirm('Restart Nexo using the imported profile? Your current profile will remain on disk.'))return;await post('transfer/switch',{profile:imported.profile,consent:true});$('navi-transfer-status').textContent='Restarting. Use the new browser tab opened by the launcher.';});
async function speak(text){const r=await post('voice/speak',{text:text.slice(0,1500),language:snapshot?.settings.voice_language||'en'});if(audioURL)URL.revokeObjectURL(audioURL);audioURL=URL.createObjectURL(new Blob([Uint8Array.from(atob(r.data),c=>c.charCodeAt(0))],{type:'audio/wav'}));$('navi-audio').src=audioURL;$('navi-audio').hidden=false;await $('navi-audio').play();}
$('navi-voice-test').onclick=attempt(()=>speak($('navi-voice-language').value==='es'?'Hola. Soy Nexo. Esta voz funciona sin internet.':'Hello. I am Nexo. This voice works without the internet.'));
$('navi-read-reply').onclick=attempt(async()=>{const last=[...conversation].reverse().find(x=>x.role==='assistant');if(!last)throw Error('Ask a question first');await speak(last.content);});
function wav(chunks,rate){const length=chunks.reduce((n,x)=>n+x.length,0),all=new Float32Array(length);let pos=0;for(const c of chunks){all.set(c,pos);pos+=c.length;}const count=Math.min(480000,Math.floor(length*16000/rate)),buffer=new ArrayBuffer(44+count*2),view=new DataView(buffer);const str=(at,text)=>{for(let i=0;i<text.length;i++)view.setUint8(at+i,text.charCodeAt(i));};str(0,'RIFF');view.setUint32(4,36+count*2,true);str(8,'WAVEfmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,16000,true);view.setUint32(28,32000,true);view.setUint16(32,2,true);view.setUint16(34,16,true);str(36,'data');view.setUint32(40,count*2,true);for(let i=0;i<count;i++){const a=Math.floor(i*rate/16000),b=Math.max(a+1,Math.floor((i+1)*rate/16000));let total=0;for(let j=a;j<b&&j<length;j++)total+=all[j];view.setInt16(44+i*2,Math.max(-1,Math.min(1,total/(b-a)))*32767,true);}return new Uint8Array(buffer);}
async function stopRecord(transcribe=true){const r=recording;if(!r)return;recording=null;clearTimeout(r.timer);r.stream.getTracks().forEach(t=>t.stop());r.worklet?.disconnect();await r.context.close();$('navi-record').textContent='Record voice';await post('listening',{active:false});if(transcribe&&r.chunks.length){$('navi-record-status').textContent='Transcribing locally…';const result=await post('voice/transcribe',{language:snapshot?.settings.voice_language||'en',data:bytes64(wav(r.chunks,r.rate))});$('prompt').value=result.text;$('prompt').focus();$('navi-record-status').textContent=result.text?'Review the transcript, then send.':'No words recognized. Try a shorter, clearer recording.';}}
$('navi-record').onclick=attempt(async()=>{if(recording)return stopRecord();if(!navigator.mediaDevices?.getUserMedia)throw Error('Microphone access requires a supported browser on localhost');const stream=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:true},video:false});let context;try{context=new AudioContext();await context.audioWorklet.addModule('/recorder.js');const worklet=new AudioWorkletNode(context,'nexo-recorder');recording={stream,context,worklet,chunks:[],rate:context.sampleRate};worklet.port.onmessage=e=>{if(recording)recording.chunks.push(e.data);};context.createMediaStreamSource(stream).connect(worklet);worklet.connect(context.destination);await context.resume();await post('listening',{active:true});recording.timer=setTimeout(()=>stopRecord().catch(e=>{$('navi-record-status').textContent=e.message;}),30000);$('navi-record').textContent='Stop recording';$('navi-record-status').textContent='Listening on this device · up to 30 seconds';}catch(e){stream.getTracks().forEach(t=>t.stop());if(context)await context.close();recording=null;throw e;}});
window.addEventListener('pagehide',()=>{if(recording){recording.stream.getTracks().forEach(t=>t.stop());recording.context.close();}if(audioURL)URL.revokeObjectURL(audioURL);});
api('/api/status').then(async s=>{if(!s.desktop)return;$('navi-tab').hidden=false;await refresh();setInterval(async()=>{if(polling||document.hidden)return;polling=true;try{const p=await api('/api/navi');snapshot=p;$('navi-voice-toolbar').hidden=!p.settings.voice;$('navi-presence').textContent='Currently '+p.presence.state;notices(p.notifications);if(p.voice.busy||p.voice.progress||p.voice.error)$('navi-voice-status').textContent=p.voice.error||p.voice.progress;}catch{}finally{polling=false;}},15000);}).catch(()=>{});
})();
