/* Device-provided offline speech only. Never fall back to server recognition. */
let recognition=null,timer=null;
export function stopVoice(){clearTimeout(timer);recognition?.abort();recognition=null;globalThis.speechSynthesis?.cancel();}
export function setupVoice({getReply,unlocked}){
 const $=id=>document.getElementById(id),notice=t=>{$('voice-status').textContent=t;};
 const run=fn=>async()=>{try{if(!unlocked())throw Error('Unlock your profile first');await fn();}catch(e){notice(e.message);}};
 function voices(){const selected=$('local-voice').value;$('local-voice').replaceChildren();for(const v of globalThis.speechSynthesis?.getVoices()||[]){if(!v.localService)continue;const o=document.createElement('option');o.value=v.voiceURI;o.textContent=v.name+' · '+v.lang;$('local-voice').append(o);}if([...$('local-voice').options].some(o=>o.value===selected))$('local-voice').value=selected;if(!$('local-voice').options.length)notice('No installed local voice is exposed by this browser. Cloud voices will not be used.');}
 globalThis.speechSynthesis?.addEventListener('voiceschanged',voices);voices();
 $('read-reply').onclick=run(()=>{const voice=globalThis.speechSynthesis?.getVoices().find(v=>v.localService&&v.voiceURI===$('local-voice').value);if(!voice)throw Error('Choose an installed local voice first');const text=getReply();if(!text)throw Error('Ask a question first');stopVoice();const u=new SpeechSynthesisUtterance(text.slice(0,1500));u.voice=voice;u.lang=voice.lang;u.onerror=()=>notice('The local voice could not finish. Try another installed voice.');speechSynthesis.speak(u);notice('Reading with an installed local voice.');});
 $('stop-speaking').onclick=()=>{stopVoice();notice('Voice stopped.');};
 function localEngine(){const R=globalThis.SpeechRecognition||globalThis.webkitSpeechRecognition;if(!R||!('processLocally'in R.prototype)||typeof R.available!=='function')throw Error('This browser does not expose on-device dictation. Use the keyboard microphone only if you accept its own privacy settings; Nexo will not use cloud recognition.');return R;}
 async function available(R){return R.available({langs:[$('voice-language').value],processLocally:true});}
 $('voice-pack').onclick=run(async()=>{const R=localEngine(),state=await available(R);if(state==='available'){notice('Offline dictation is ready.');return;}if(state!=='downloadable'||typeof R.install!=='function')throw Error('Offline dictation is unavailable or still downloading for this language');if(!confirm('Download the browser’s on-device language pack? This needs an internet connection once.'))return;notice('Installing the browser’s offline language pack…');if(!await R.install({langs:[$('voice-language').value],processLocally:true}))throw Error('Language pack installation did not complete');notice('Offline language pack installed.');});
 $('dictate').onclick=run(async()=>{if(recognition){recognition.stop();return;}const R=localEngine();if(await available(R)!=='available')throw Error('Check or install an offline language pack first');const r=new R();r.processLocally=true;if(r.processLocally!==true)throw Error('On-device recognition could not be required');r.lang=$('voice-language').value;r.continuous=false;r.interimResults=false;r.maxAlternatives=1;recognition=r;r.onresult=e=>{if(!unlocked())return;const text=e.results[0]?.[0]?.transcript||'';$('prompt').value=text.slice(0,1200);notice('Review the transcript, then press Send.');};r.onerror=e=>notice('Local dictation could not finish: '+e.error);r.onend=()=>{clearTimeout(timer);recognition=null;$('dictate').textContent='Dictate locally';};r.start();$('dictate').textContent='Stop dictation';notice('Listening locally for up to 30 seconds…');timer=setTimeout(()=>r.stop(),30000);});
 document.addEventListener('visibilitychange',()=>{if(document.hidden)stopVoice();});globalThis.addEventListener('pagehide',stopVoice);
}
