// Real browser: encrypted desktop interop, on-device WASM inference and offline reload.
const {chromium,webkit}=require(process.env.NEXO_PLAYWRIGHT_MODULE||'playwright');
const http=require('http'),fs=require('fs'),path=require('path'),assert=require('assert');
const {spawnSync}=require('child_process');
const root=path.resolve(__dirname,'..'),output=path.join(root,'reports/mobile');fs.mkdirSync(output,{recursive:true});
const fixture=path.join(output,'test-profile.nexo');
const py=spawnSync(process.env.NEXO_PYTHON||'python',['-c',`import sys,json,tempfile;from pathlib import Path;from nexo7.store import Store;from nexo7.transfer import export_profile\nwith tempfile.TemporaryDirectory() as d:\n s=Store(Path(d)/'nexo.sqlite3');s.trust.set_scope('transfer.export',True);s.add_document('Desktop test note','This came from the desktop.');s.continuity.configure({'name':'Luna','onboarded':True});s.continuity.save({'what':'Finished the violet project','people':'Ana','pinned':True});Path(sys.argv[1]).write_text(json.dumps(export_profile(s,[],'browser test pairing phrase')));s.close()`,fixture],{cwd:root,encoding:'utf8'});assert.equal(py.status,0,py.stderr);
const mime={'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.wasm':'application/wasm','.webmanifest':'application/manifest+json'};
const server=http.createServer((req,res)=>{const name=decodeURIComponent(req.url.split('?')[0]);const file=path.resolve(root,'mobile/dist','.'+(name==='/'?'/index.html':name));if(!file.startsWith(path.join(root,'mobile/dist')+path.sep)||!fs.existsSync(file)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',mime[path.extname(file)]||'application/octet-stream');if(process.env.NEXO_MOBILE_COMPAT&&path.basename(file)==='inference.js'){res.end("Object.defineProperty(WebAssembly,'Suspending',{value:undefined,configurable:true});\n"+fs.readFileSync(file,'utf8'));return;}fs.createReadStream(file).pipe(res);});
let browser,reviewPage;
(async()=>{try{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;
 browser=process.env.NEXO_BROWSER==='webkit'?await webkit.launch({headless:true}):await chromium.launch({headless:true,executablePath:process.env.NEXO_CHROME||undefined,args:['--no-sandbox']});
 const context=await browser.newContext({viewport:{width:390,height:844},...(process.env.NEXO_MOBILE_COMPAT?{userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 26_0 like Mac OS X) AppleWebKit/605.1.15 Version/26.0 Mobile/15E148 Safari/604.1'}:{})});const page=await context.newPage(),errors=[];reviewPage=page;page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(['error','warning'].includes(m.type()))process.stderr.write(m.text().slice(0,250)+'\n');});
 if(process.env.NEXO_MOBILE_MODEL_FIXTURE){await context.route('https://huggingface.co/**',async route=>{const requested=new URL(route.request().url()).pathname.split('/resolve/')[1]?.split('/').slice(1).join('/');const file=path.join(process.env.NEXO_MOBILE_MODEL_FIXTURE,requested||'missing');if(!requested||!fs.existsSync(file))return route.fulfill({status:404,body:'not found',headers:{'access-control-allow-origin':'*'}});return route.fulfill({status:200,path:file,headers:{'access-control-allow-origin':'*','content-type':requested.endsWith('.json')?'application/json':'application/octet-stream'}});});}
 await page.goto(url);await page.locator('#phrase').fill('browser test pairing phrase');await page.locator('#import').setInputFiles(fixture);await page.locator('#home').waitFor({state:'visible'});
 assert.equal(await page.locator('#navi-name').innerText(),'Luna');await page.locator('[data-tab=notes]').click();await page.locator('#experience-list').getByText('Finished the violet project',{exact:true}).waitFor();assert((await page.locator('#note-list').innerText()).includes('Desktop test note'));await page.locator('#note-title').fill('<img src=x onerror=alert(1)>');await page.locator('#note-text').fill('Mobile note');await page.locator('#note-form button').click();await page.getByText('Note encrypted and saved on this device.',{exact:true}).waitFor();assert.equal(await page.locator('#note-list img').count(),0);
 await page.locator('[data-tab=settings]').click();const downloadPromise=page.waitForEvent('download');await page.locator('#export').click();const download=await downloadPromise;const exported=path.join(output,'roundtrip.nexo');await download.saveAs(exported);
 const verify=spawnSync(process.env.NEXO_PYTHON||'python',['-c',`import sys,json;from nexo7.transfer import decrypt\np=decrypt(json.load(open(sys.argv[1])),'browser test pairing phrase');assert len(p['documents'])==2;assert p['documents'][1]['content']=='Mobile note';assert p['persona']['name']=='Luna';assert p['episodes'][0]['people']=='Ana';print('Python-browser-Python encrypted transfer passed')`,exported],{cwd:root,encoding:'utf8'});assert.equal(verify.status,0,verify.stderr);
 await page.locator('[data-tab=day]').click();await page.locator('#reminder-text').fill('Test reminder');await page.locator('#reminder-time').fill('2026-01-01T10:00');await page.locator('#reminder-form button').click();await page.getByText('Test reminder',{exact:true}).waitFor();
 await page.screenshot({path:path.join(output,'mobile-day.png'),fullPage:true});
 await page.locator('[data-tab=settings]').click();
 await page.locator('#browser-palette').selectOption('violet');await page.locator('#browser-theme').selectOption('dark');await page.locator('#browser-avatar').selectOption('cat');
 await page.locator('[data-tab=studio]').click();
 const picture=spawnSync(process.env.NEXO_PYTHON||'python',['-c',`from PIL import Image;import sys;Image.new('RGBA',(80,40),(200,70,20,255)).save(sys.argv[1])`,path.join(output,'input.png')],{encoding:'utf8'});assert.equal(picture.status,0,picture.stderr);
 const unexpected=[];page.on('request',r=>{if(!r.url().startsWith(url)&&!r.url().startsWith('blob:')&&!r.url().startsWith('data:'))unexpected.push(r.url());});
 await page.locator('#studio-file').setInputFiles(path.join(output,'input.png'));await page.locator('#studio-download').waitFor({state:'visible'});await page.waitForFunction(()=>!document.querySelector('#studio-download').disabled);
 await page.locator('#studio-rotate').click();assert.deepEqual(await page.locator('#studio-canvas').evaluate(c=>[c.width,c.height]),[40,80]);
 await page.locator('#studio-undo').click();assert.deepEqual(await page.locator('#studio-canvas').evaluate(c=>[c.width,c.height]),[80,40]);
 await page.locator('#studio-gray').click();const pixel=await page.locator('#studio-canvas').evaluate(c=>Array.from(c.getContext('2d').getImageData(0,0,1,1).data));assert.equal(pixel[0],pixel[1]);assert.equal(pixel[1],pixel[2]);
 await page.locator('#studio-erase').check();await page.locator('#studio-canvas').click({position:{x:20,y:20}});
 const pngPromise=page.waitForEvent('download');await page.locator('#studio-download').click();const png=await pngPromise;await png.saveAs(path.join(output,'edited.png'));
 const alpha=spawnSync(process.env.NEXO_PYTHON||'python',['-c',`from PIL import Image;import sys;im=Image.open(sys.argv[1]);assert im.mode=='RGBA';assert im.getextrema()[3][0]==0`,path.join(output,'edited.png')],{encoding:'utf8'});assert.equal(alpha.status,0,alpha.stderr);
 assert.deepEqual(unexpected,[],'Image editing must not make external requests');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.screenshot({path:path.join(output,'local-image-studio.png'),fullPage:true});
 await page.locator('[data-tab=chat]').click();await page.locator('#model').click();await page.waitForFunction(()=>document.querySelector('#model-status').textContent.includes('Ready')||(!document.querySelector('#model').disabled&&document.querySelector('#send').disabled),{},{timeout:240000});assert.equal(await page.locator('#send').isEnabled(),true,await page.locator('#status').innerText());
 await page.locator('#prompt').fill('What is a chicken?');await page.locator('#send').click();await page.locator('#stop').waitFor({state:'hidden',timeout:120000});const answer=await page.locator('.assistant').last().innerText();assert(/bird|poultry|domesticat|eggs?/i.test(answer)&&!/corvidae|marine|fish|Phryidae|Chiroptera|Chondrichamphue/i.test(answer),'Definition check failed: '+answer);

 await page.locator('#read-reply').locator('..').evaluate(e=>e.open=true);
 await page.evaluate(()=>{window.SpeechSynthesisUtterance=class{constructor(text){this.text=text;}};speechSynthesis.getVoices=()=>[{voiceURI:'remote-test',name:'Remote',lang:'en-US',localService:false},{voiceURI:'local-test',name:'Local test',lang:'en-US',localService:true}];speechSynthesis.speak=u=>{window.testVoiceURI=u.voice.voiceURI;};speechSynthesis.dispatchEvent(new Event('voiceschanged'));});
 assert.equal(await page.locator('#local-voice option').count(),1);await page.locator('#read-reply').click();assert.equal(await page.evaluate(()=>window.testVoiceURI),'local-test');
 await page.evaluate(()=>{class LocalSpeech{static async available(){return 'available';}start(){window.localSpeechRequired=this.processLocally;queueMicrotask(()=>{this.onresult({results:[[{transcript:'Reviewed local words'}]]});this.onend();});}abort(){}stop(){this.onend?.();}}LocalSpeech.prototype.processLocally=false;window.SpeechRecognition=LocalSpeech;});
 const beforeDictation=await page.locator('.assistant').count();await page.locator('#dictate').click();await page.waitForFunction(()=>document.querySelector('#prompt').value==='Reviewed local words');assert.equal(await page.evaluate(()=>window.localSpeechRequired),true);assert.equal(await page.locator('.assistant').count(),beforeDictation);
 await page.evaluate(()=>{window.SpeechRecognition=class RemoteOnly{start(){window.remoteSpeechStarted=true;}};});await page.locator('#dictate').click();await page.locator('#voice-status').filter({hasText:'does not expose on-device dictation'}).waitFor();assert.equal(await page.evaluate(()=>!!window.remoteSpeechStarted),false);await page.locator('#prompt').fill('');
 await page.screenshot({path:path.join(output,'mobile-chat.png'),fullPage:true});
 await page.waitForFunction(()=>!!navigator.serviceWorker.controller,{},{timeout:30000});await context.setOffline(true);await page.reload();await page.locator('#phrase').fill('browser test pairing phrase');await page.locator('#unlock').click();await page.locator('#home').waitFor({state:'visible'});assert.equal(await page.locator('#navi-name').innerText(),'Luna');assert.equal(await page.locator('html').getAttribute('data-palette'),'violet');assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');assert.equal(await page.locator('html').getAttribute('data-avatar'),'cat');assert((await page.locator('#alerts').textContent()).includes('Test reminder'));await page.locator('#model').click();await page.waitForFunction(()=>document.querySelector('#model-status').textContent.includes('Ready')||(!document.querySelector('#model').disabled&&document.querySelector('#send').disabled),{},{timeout:120000});assert.equal(await page.locator('#send').isEnabled(),true,await page.locator('#status').innerText());await page.locator('#prompt').fill('Say hello.');await page.locator('#send').click();await page.locator('#stop').waitFor({state:'hidden',timeout:120000});assert((await page.locator('.assistant').last().innerText()).length>0);
 await page.locator('#lock').click();await page.locator('#welcome').waitFor({state:'visible'});assert.equal(await page.locator('#note-list').innerText(),'');assert.equal(await page.locator('#experience-list').innerText(),'');assert.equal(await page.locator('#alerts').innerText(),'');assert.equal(await page.locator('#studio-canvas').isVisible(),false);assert.deepEqual(errors,[]);fs.writeFileSync(path.join(output,'result.json'),JSON.stringify({passed:true,checks:['browser execution without app install','palette/theme/avatar persist','manual image editing and PNG transparency without network','local-only voice selection and reviewed dictation with mocked browser capabilities','remote-only recognition rejected','persona and experience transfer','notification inbox survives offline reload','Python/browser encrypted roundtrip','literal note rendering','reminder delivery','real CPU WASM generation','offline reload and generation','profile lock'],sample:answer},null,2));console.log('Mobile browser checks passed.');
 }catch(e){if(reviewPage){console.error('UI status:',await reviewPage.locator('#status').innerText().catch(()=>''),'Model:',await reviewPage.locator('#model-status').innerText().catch(()=>''));await reviewPage.screenshot({path:path.join(output,'failure.png'),fullPage:true}).catch(()=>{});}throw e;}finally{if(browser)await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
