// Real browser: encrypted desktop interop, on-device WASM inference and offline reload.
const {chromium}=require(process.env.NEXO_PLAYWRIGHT_MODULE||'playwright');
const http=require('http'),fs=require('fs'),path=require('path'),assert=require('assert');
const {spawnSync}=require('child_process');
const root=path.resolve(__dirname,'..'),output=path.join(root,'reports/mobile');fs.mkdirSync(output,{recursive:true});
const fixture=path.join(output,'test-profile.nexo');
const py=spawnSync(process.env.NEXO_PYTHON||'python',['-c',`import sys,json,tempfile;from pathlib import Path;from nexo7.store import Store;from nexo7.transfer import export_profile\nwith tempfile.TemporaryDirectory() as d:\n s=Store(Path(d)/'nexo.sqlite3');s.trust.set_scope('transfer.export',True);s.add_document('Desktop test note','This came from the desktop.');Path(sys.argv[1]).write_text(json.dumps(export_profile(s,[],'browser test pairing phrase')));s.close()`,fixture],{cwd:root,encoding:'utf8'});assert.equal(py.status,0,py.stderr);
const mime={'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.wasm':'application/wasm','.webmanifest':'application/manifest+json'};
const server=http.createServer((req,res)=>{const name=decodeURIComponent(req.url.split('?')[0]);const file=path.resolve(root,'mobile/dist','.'+(name==='/'?'/index.html':name));if(!file.startsWith(path.join(root,'mobile/dist')+path.sep)||!fs.existsSync(file)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',mime[path.extname(file)]||'application/octet-stream');fs.createReadStream(file).pipe(res);});
let browser;
(async()=>{try{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;
 browser=await chromium.launch({headless:true,executablePath:process.env.NEXO_CHROME||undefined,args:['--no-sandbox']});
 const context=await browser.newContext({viewport:{width:390,height:844}});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')process.stderr.write(m.text().slice(0,250)+'\n');});
 if(process.env.NEXO_MOBILE_MODEL_FIXTURE){await context.route('https://huggingface.co/**',async route=>{const requested=new URL(route.request().url()).pathname.split('/resolve/')[1]?.split('/').slice(1).join('/');const file=path.join(process.env.NEXO_MOBILE_MODEL_FIXTURE,requested||'missing');if(!requested||!fs.existsSync(file))return route.fulfill({status:404,body:'not found',headers:{'access-control-allow-origin':'*'}});return route.fulfill({status:200,path:file,headers:{'access-control-allow-origin':'*','content-type':requested.endsWith('.json')?'application/json':'application/octet-stream'}});});}
 await page.goto(url);await page.locator('#phrase').fill('browser test pairing phrase');await page.locator('#import').setInputFiles(fixture);await page.locator('#home').waitFor({state:'visible'});
 await page.locator('[data-tab=notes]').click();assert((await page.locator('#note-list').innerText()).includes('Desktop test note'));await page.locator('#note-title').fill('<img src=x onerror=alert(1)>');await page.locator('#note-text').fill('Mobile note');await page.locator('#note-form button').click();await page.getByText('Note encrypted and saved on this device.',{exact:true}).waitFor();assert.equal(await page.locator('#note-list img').count(),0);
 await page.locator('[data-tab=settings]').click();const downloadPromise=page.waitForEvent('download');await page.locator('#export').click();const download=await downloadPromise;const exported=path.join(output,'roundtrip.nexo');await download.saveAs(exported);
 const verify=spawnSync(process.env.NEXO_PYTHON||'python',['-c',`import sys,json;from nexo7.transfer import decrypt\np=decrypt(json.load(open(sys.argv[1])),'browser test pairing phrase');assert len(p['documents'])==2;assert p['documents'][1]['content']=='Mobile note';print('Python-browser-Python encrypted transfer passed')`,exported],{cwd:root,encoding:'utf8'});assert.equal(verify.status,0,verify.stderr);
 await page.locator('[data-tab=day]').click();await page.locator('#reminder-text').fill('Test reminder');await page.locator('#reminder-time').fill('2026-01-01T10:00');await page.locator('#reminder-form button').click();await page.getByText('Reminder: Test reminder',{exact:true}).waitFor();
 await page.screenshot({path:path.join(output,'mobile-day.png'),fullPage:true});
 await page.locator('[data-tab=chat]').click();await page.locator('#model').click();await page.waitForFunction(()=>document.querySelector('#model-status').textContent.includes('Ready')||document.querySelector('#status').textContent.includes('backend'),{},{timeout:240000});assert.equal(await page.locator('#send').isEnabled(),true,await page.locator('#status').innerText());
 await page.locator('#prompt').fill('What is a chicken?');await page.locator('#send').click();await page.locator('#stop').waitFor({state:'hidden',timeout:120000});const answer=await page.locator('.assistant').last().innerText();assert(answer.length>10,answer);
 await page.screenshot({path:path.join(output,'mobile-chat.png'),fullPage:true});
 await page.evaluate(()=>navigator.serviceWorker.ready);await context.setOffline(true);await page.reload();await page.locator('#phrase').fill('browser test pairing phrase');await page.locator('#unlock').click();await page.locator('#home').waitFor({state:'visible'});await page.locator('#model').click();await page.waitForFunction(()=>document.querySelector('#model-status').textContent.includes('Ready'),{},{timeout:120000});await page.locator('#prompt').fill('Say hello.');await page.locator('#send').click();await page.locator('#stop').waitFor({state:'hidden',timeout:120000});assert((await page.locator('.assistant').last().innerText()).length>0);
 await page.locator('#lock').click();await page.locator('#welcome').waitFor({state:'visible'});assert.equal(await page.locator('#note-list').innerText(),'');assert.deepEqual(errors,[]);fs.writeFileSync(path.join(output,'result.json'),JSON.stringify({passed:true,checks:['Python/browser encrypted roundtrip','literal note rendering','reminder delivery','real CPU WASM generation','offline reload and generation','profile lock'],sample:answer},null,2));console.log('Mobile browser checks passed.');
 }finally{if(browser)await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
