const {JSDOM,VirtualConsole}=require(process.env.NEXO_JSDOM_MODULE || 'jsdom');
const path=require('path'), os=require('os');
const root=path.resolve(__dirname,'..');
const fs=require('fs');
const assert=require('assert');
const directory=fs.mkdtempSync(path.join(os.tmpdir(),'nexo-ui-'));
const child=require('child_process').spawn(process.env.NEXO_PYTHON || (process.platform==='win32'?'python':'python3'),['-c',"from unittest.mock import patch\nfrom nexo7.desktop import main\nwith patch('nexo7.setup.native_plan', side_effect=ValueError('Insufficient free memory (UI test fixture)')), patch('nexo7.web_research.fetch_json', return_value={'query':{'pages':{'1':{'title':'Network fixture','extract':'Devices exchange data over a network.'}}}}):\n    main()\n",'--no-open','--data-dir',directory],{cwd:root,stdio:'ignore'});
child.on('exit',()=>fs.rmSync(directory,{recursive:true,force:true}));
let access;
const errors=[];
const virtualConsole=new VirtualConsole();
virtualConsole.on('jsdomError',e=>errors.push(e.message));
async function waitFor(predicate,ms=10000){const end=Date.now()+ms;while(!predicate()){if(Date.now()>end)throw new Error('UI state did not arrive');await new Promise(r=>setTimeout(r,50));}}
(async()=>{
 await waitFor(()=>fs.existsSync(directory+'/access.json'));
 access=JSON.parse(fs.readFileSync(directory+'/access.json','utf8'));
 const dom=await JSDOM.fromURL(access.url,{runScripts:'dangerously',resources:'usable',pretendToBeVisual:true,virtualConsole,
 beforeParse(w){w.URL.createObjectURL=()=> 'blob:nexo-test';w.URL.revokeObjectURL=()=>{};w.fetch=(url,opts)=>fetch(new URL(url,access.url),opts);w.HTMLElement.prototype.scrollIntoView=function(){};w.confirm=()=>true;}});
 const w=dom.window,d=w.document;
 try {
  await waitFor(()=>d.getElementById('setup-view')&&!d.getElementById('setup-view').hidden);
  assert.equal(d.documentElement.lang,'en');
  d.getElementById('check-system').click();
  await waitFor(()=>d.getElementById('setup-requirements').textContent.includes('Insufficient free memory'));
  assert(d.getElementById('start-local').disabled);
  d.getElementById('try-demo').click();
  assert(d.getElementById('setup-view').hidden);
  assert.equal(d.getElementById('mode').value,'companion');
  assert(!d.getElementById('chat-options').open);assert(d.getElementById('web-controls').hidden);
  d.getElementById('theme-toggle').click();assert.equal(d.documentElement.dataset.theme,'dark');
  d.getElementById('theme-toggle').click();
  d.getElementById('open-scenario').click();assert(d.getElementById('scenario-panel').open);
  d.getElementById('scenario-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
  await waitFor(()=>d.getElementById('scenario-result').textContent.includes('10.1937'));
  d.getElementById('scenario-kind').value='cost';d.getElementById('scenario-kind').onchange();
  d.getElementById('scenario-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
  await waitFor(()=>d.getElementById('scenario-result').textContent.includes('120.00'));
  d.getElementById('mode').value='research';
  d.getElementById('mode').onchange();
  d.getElementById('new').click();
  assert.equal(d.getElementById('mode').value,'companion');
  assert(d.getElementById('research-notice').hidden);
  d.getElementById('prompt').value='/calc 24.5 * 40';
  d.getElementById('composer').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
  await waitFor(()=>[...d.querySelectorAll('.assistant .message-text')].some(e=>e.textContent==='980.0'));
  d.getElementById('memory-tab').click();
  d.getElementById('doc-title').value='UI integration fixture';
  d.getElementById('doc-content').value='<img src=x onerror=alert(1)> Test fixture with literal HTML.';
  d.getElementById('memory-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
  await waitFor(()=>[...d.querySelectorAll('.document-card h3')].some(e=>e.textContent==='UI integration fixture'));
  assert(!d.querySelector('.document-card img'));
  d.getElementById('chat-tab').click();
  assert(!d.getElementById('chat-view').hidden);
  d.getElementById('setup-tab').click();
  assert(!d.getElementById('setup-view').hidden);
  d.getElementById('performance').value='fast';
  d.getElementById('reply-style').value='detailed';
  d.getElementById('personality').value='friendly';d.getElementById('adapt-tone').checked=true;
  d.getElementById('save-preferences').click();
  await waitFor(()=>d.getElementById('preferences-status').textContent.includes('Saved.'));
  const privateURL=new URL(access.url);
  const key=new URLSearchParams(privateURL.hash.slice(1)).get('token');
  const request=async(route,method='GET',body)=>{
   const response=await fetch(new URL(route,access.url),{method,headers:{'X-Nexo-Key':key,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});
   assert(response.ok,route+' '+response.status);return response.json();
  };
  assert.equal((await request('/api/preferences')).performance,'fast');
  const images=await request('/api/images');assert.equal(images.installed,false);
  d.getElementById('diffusion-open').click();await waitFor(()=>!d.getElementById('workspace-view').hidden);
  assert(d.getElementById('diffusion-generate').disabled);assert(!d.getElementById('diffusion-use').checked);
  d.getElementById('diffusion-install').click();await waitFor(()=>d.getElementById('diffusion-status').textContent.includes('no image engine'));
  assert.equal((await request('/api/images')).phase,'idle');
  assert.equal((await request('/api/preferences')).personality,'friendly');
  assert.equal((await request('/api/preferences')).adapt_tone,true);
  const word=await request('/api/export/document','POST',{title:'Offline notes',content:'# Review\nA local document.'});
  assert.equal(Buffer.from(word.data,'base64').subarray(0,2).toString(),'PK');
  const unauthorized=await fetch(new URL('/api/artifacts',access.url));assert.equal(unauthorized.status,401);
  d.getElementById('chat-tab').click();
  const useful=[...d.querySelectorAll('.assistant button')].find(b=>b.textContent.includes('useful'));
  assert(useful);useful.click();
  await waitFor(()=>useful.disabled);
  assert((await request('/api/documents')).documents.some(x=>x.source.includes('user-approved')));
  d.getElementById('workspace-tab').click();
  d.getElementById('creative-render').click();
  await waitFor(()=>d.querySelector('#creative-output img'));
  assert.equal(d.querySelectorAll('#creative-output a').length,2);
  d.getElementById('creative-kind').value='music';d.getElementById('creative-kind').onchange();
  d.getElementById('creative-render').click();
  await waitFor(()=>d.querySelector('#creative-output audio'));
  assert.equal(d.querySelectorAll('#creative-output a')[1].download,'music.mid');
  d.getElementById('creative-spec').value='{}';d.getElementById('creative-render').click();
  await waitFor(()=>d.getElementById('creative-status').textContent.includes('notes'));
  assert(!d.getElementById('creative-render').disabled);
  const creativeUnauthorized=await fetch(new URL('/api/creative',access.url),{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});
  assert.equal(creativeUnauthorized.status,401);
  d.getElementById('task-template').value='web';d.getElementById('task-template').onchange();
  assert(d.getElementById('task-steps').value.includes('html_structure,inline_style'));
  assert(d.getElementById('model-choice').querySelector('option[value="lfm2-vl:450m"]'));
  assert(d.getElementById('chat-images'));
  d.getElementById('task-goal').value='Write a project guide';
  d.getElementById('task-steps').value='guide.md | Write a short guide | Guide';
  d.getElementById('task-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
  await waitFor(()=>d.getElementById('tasks').textContent.includes('Write a project guide'));
  assert.equal((await request('/api/tasks')).tasks.length,1);
  [...d.querySelectorAll('#tasks button')].find(b=>b.textContent==='Delete task history').click();
  await waitFor(()=>!d.getElementById('tasks').textContent.includes('Write a project guide'));
  d.getElementById('artifact-name').value='example.py';
  d.getElementById('artifact-content').value='print("review before running")';
  d.getElementById('artifact-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
  await waitFor(()=>d.getElementById('artifacts').textContent.includes('example.py'));
  const saved=(await request('/api/artifacts')).artifacts[0];
  assert.equal((await request('/api/artifacts/'+saved.id)).content,'print("review before running")');
  const remove=[...d.querySelectorAll('#artifacts button')].find(b=>b.textContent.includes('Delete'));
  assert(remove);remove.click();
  await waitFor(()=>!d.getElementById('artifacts').textContent.includes('example.py'));
  const imported=await request('/api/import','POST',{name:'notes.txt',data:Buffer.from('Offline document import').toString('base64')});
  assert.equal(imported.content,'Offline document import');
  const checked=await request('/api/artifacts','POST',{name:'sales.csv',content:'amount\n10\n20\n'});
  assert.equal(checked.verification.rows,2);
  const broken=await request('/api/artifacts','POST',{name:'broken.py',content:'def f(:'});
  assert.equal(broken.verification.syntax_valid,false);
  const device=await request('/api/chat','POST',{message:'/device',mode:'companion',private:true});
  assert.equal(device.stats.model_calls,0);assert(device.device.total_bytes>0);
  const summary=await request('/api/inspect','POST',{filename:'sales.csv'});
  assert.equal(summary.columns[0].sum,'30');
  d.getElementById('memory-tab').click();
  d.getElementById('learn-question').value='Explain local learning fixture';
  d.getElementById('learn-answer').value='Reviewed answer <img src=x onerror=alert(1)>';
  d.getElementById('learn-language').value='en';
  d.getElementById('learn-consent').checked=true;
  d.getElementById('learning-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
  await waitFor(()=>d.getElementById('learning-entries').textContent.includes('Explain local learning fixture'));
  assert(!d.querySelector('#learning-entries img'));
  assert.equal((await request('/api/learning')).entries.length,1);
  d.getElementById('share-consent').checked=true;
  d.getElementById('prepare-contribution').click();
  await waitFor(()=>d.querySelector('#contribution-preview a'));
  assert(d.querySelector('#contribution-preview a').href.startsWith('https://github.com/xatusbetazx17/Nexo7/issues/new?'));
  d.getElementById('learn-answer').dispatchEvent(new w.Event('input',{bubbles:true}));
  assert(!d.getElementById('share-consent').checked);
  assert(!d.querySelector('#contribution-preview a'));
  d.getElementById('community-learning').click();
  await waitFor(()=>d.getElementById('learning-preview').textContent.includes('nexo-learning-v1'));
  assert.equal((await request('/api/learning')).entries.length,1);
  d.getElementById('pack-consent').checked=true;
  d.getElementById('import-learning').click();
  await waitFor(()=>d.getElementById('learning-status').textContent.includes('Imported 2'));
  assert.equal((await request('/api/learning')).entries.length,3);
  await waitFor(()=>d.querySelectorAll('[data-learning-id]').length===3);
  d.getElementById('reply-style').value='accessible';
  d.getElementById('preferences-status').textContent='';
  d.getElementById('save-preferences').click();
  await waitFor(()=>d.getElementById('preferences-status').textContent.includes('Saved.'));
  assert.equal((await request('/api/preferences')).style,'accessible');

  d.getElementById('chat-tab').click();
  d.getElementById('mode').value='web';d.getElementById('mode').dispatchEvent(new w.Event('change'));
  assert(!d.getElementById('web-controls').hidden);
  d.getElementById('remember-web').checked=true;d.getElementById('synthesize-web').checked=false;
  d.getElementById('prompt').value='Network fixture';
  d.getElementById('composer').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
  await waitFor(()=>!d.getElementById('send').disabled);
  assert(d.getElementById('messages').textContent.includes('Devices exchange data'));
  assert.equal((await request('/api/web')).sources.length,1);
  assert.equal(d.getElementById('mode').value,'companion');
  d.getElementById('mode').value='web';d.getElementById('mode').onchange();
  d.getElementById('prompt').value='Network fixture';
  d.getElementById('composer').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
  await waitFor(()=>!d.getElementById('send').disabled);
  assert(d.getElementById('messages').textContent.includes('Saved sources reused'));
  d.getElementById('memory-tab').click();
  await waitFor(()=>d.getElementById('web-sources').textContent.includes('Network fixture'));
  [...d.querySelectorAll('#web-sources button')].find(b=>b.textContent==='Contribute a note').click();
  d.getElementById('note-question').value='What is a home network?';
  d.getElementById('note-answer').value='A home network connects household equipment so it can communicate.';
  d.getElementById('note-rights').value='I wrote this explanation myself.';
  for(const id of ['note-own','note-private','note-publish'])d.getElementById(id).checked=true;
  d.getElementById('note-prepare').click();
  await waitFor(()=>d.querySelector('#note-preview a'));
  assert(d.querySelector('#note-preview a').href.startsWith('https://github.com/xatusbetazx17/Nexo7/issues/new?'));
  assert(!d.getElementById('note-preview').textContent.includes('Devices exchange data over a network.'));
  assert(d.getElementById('note-status').textContent.includes('Nothing has been uploaded'));
  d.getElementById('note-answer').dispatchEvent(new w.Event('input',{bubbles:true}));
  assert(!d.getElementById('note-publish').checked);assert(!d.querySelector('#note-preview a'));
  d.getElementById('chat-tab').click();
  d.getElementById('math-run').click();
  await waitFor(()=>d.getElementById('math-result').textContent.includes('roots'));
  assert.deepEqual(JSON.parse(d.getElementById('math-result').textContent).roots.sort(),['2','3']);
  d.getElementById('math-operation').value='linear';d.getElementById('math-operation').onchange();
  assert(!d.getElementById('math-vector').hidden);d.getElementById('math-run').click();
  await waitFor(()=>d.getElementById('math-result').textContent.includes('solution'));
  assert.deepEqual(JSON.parse(d.getElementById('math-result').textContent).solution.map(Number),[2,1]);
  d.getElementById('memory-tab').click();
  [...d.querySelectorAll('#web-sources button')].find(b=>b.textContent==='Review for local learning').click();
  assert(d.getElementById('learning-source-note').textContent.includes('wikipedia.org'));
  d.getElementById('learn-question').value='How can home equipment communicate?';
  d.getElementById('learn-answer').value='It can exchange information over a network.';
  d.getElementById('learn-consent').checked=true;
  d.getElementById('learning-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
  await waitFor(()=>d.getElementById('learning-entries').textContent.includes('How can home equipment communicate?'));
  assert((await request('/api/learning')).entries.some(e=>e.provenance&&e.provenance.url.includes('wikipedia.org')));
  d.getElementById('clear-web-sources').click();
  await waitFor(()=>!d.getElementById('web-sources').textContent.includes('Network fixture'));
  assert.equal((await request('/api/web')).sources.length,0);
  assert.deepEqual(errors,[]);
  const result={environment:'JSDOM with real local HTTP server; not a rendered-browser layout test',passed:true,checks:['English setup view','low-memory explanation','download disabled without prerequisites','demo navigation','calculator response','document import','literal HTML handling','setup navigation','persistent preferences','explicitly approved example','authenticated artifact API','workspace create/read/delete','persistent task plan UI and deletion','bounded text import','CSV analysis','reviewed learning creation','literal learning HTML','consent resets on edit','public draft without automatic upload','community pack review and import','opt-in web lookup with fixture provider','saved web reuse','personality preferences persist','local DOCX export','source-linked reviewed learning','original-note draft and consent reset','offline quadratic and linear math UI','web source deletion','offline PNG/SVG and WAV/MIDI previews and validation','simple chat defaults and single-message search','theme switching','explicit what-if calculations','no JavaScript errors']};
  fs.mkdirSync(path.join(root,'reports'),{recursive:true});
  fs.writeFileSync(path.join(root,'reports/ui-integration.json'),JSON.stringify(result,null,2));
  console.log(JSON.stringify(result));
 } finally {w.close();child.kill('SIGINT');}

})().catch(e=>{console.error(e);child.kill('SIGKILL');process.exitCode=1;});
